### PR TITLE
Add content on the VS Code extension

### PR DESCRIPTION
**Pull request by Chuxel**
This PR adds inital content on using the VS Code extension now that its published.

### CODE REVIEW

**Comment by Chuxel** [comment]
Not sure why the images aren't showing up right in the preview. If you go to the actual branch, things look correct.

**Review by lostintangent — APPROVED** [review]

**Comment by Celebrum** [comment]
/improve
--pr_code_suggestions.extra_instructions="
Additional instructions:
- 
"
--pr_code_suggestions.num_code_suggestions_per_chunk="10"
--pr_code_suggestions.commitable_code_suggestions=true
--pr_code_suggestions.suggestions_score_threshold="0"

**Comment by Celebrum** [comment]
/describe
--pr_description.publish_labels=true
--pr_description.publish_description_as_comment=true
--pr_description.generate_ai_title=true
--pr_description.final_update_message=true

**Comment by Celebrum** [comment]
This pull request includes updates to the `README.md` file and the addition of a new `vscode.md` file to provide comprehensive documentation for the GitHub Copilot Workspace VS Code extension. The changes enhance the user guide and add detailed instructions for using the extension.

Documentation updates:

* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L10-R10): Updated the link for the VS Code section to point to the new `vscode.md` file and added an extension link.

New documentation:

* [`vscode.md`](diffhunk://#diff-265fef2efb3bc9246c583efc0ac54752bc8714754b1b45c9054ada83381974cbR1-R190): Added a detailed guide for the GitHub Copilot Workspace VS Code extension, including sections on getting started, browsing sessions, managing sessions, planning and implementing, natural language revisions, and known limitations.

**Comment by Celebrum** [comment]
/add_docs
--pr_add_docs.extra_instructions="
Extra instructions:
start a connection whit mu gitbook connection
- where each tool open source will be present and link to the owner github readme we us have a tutoriel on how to use and implement
-use the app link of gitbook / github
--pr_add_docs.docs_style=
"
--pr_add_docs.docs_style="google style guides"

**Pull request merged**
